Repository wondrous-dev/wondrous-frontend, pull requests merged in 2022-09, with the labels that each got.

#926 feat: add wallet address to members table
  wondrous-app/components/Common/dropdown.tsx
  wondrous-app/components/Icons/checkMark.tsx
  wondrous-app/components/Icons/podIcon.tsx
  wondrous-app/components/Icons/podIconWithoutBg.tsx
  wondrous-app/components/Icons/taskMenu.tsx
  wondrous-app/components/Settings/MemberRoles/index.tsx
  wondrous-app/components/Settings/MemberRoles/styled.tsx
  wondrous-app/components/Settings/Members/MemberRoleDropdown.tsx
  wondrous-app/components/Settings/Members/MembersTableRow/MemberRoleSelectionDropdown.tsx
  wondrous-app/components/Settings/Members/MembersTableRow/helpers.ts
  wondrous-app/components/Settings/Members/MembersTableRow/index.tsx
  wondrous-app/components/Settings/Members/MembersTableRow/styles.tsx
  wondrous-app/components/Settings/Members/helpers.tsx
  wondrous-app/components/Settings/Members/index.tsx
  wondrous-app/components/Settings/Members/styles.tsx
  wondrous-app/components/Settings/headerBlock.tsx
  wondrous-app/components/Settings/styles.tsx
  wondrous-app/graphql/queries/org.ts
  wondrous-app/graphql/queries/pod.ts
  wondrous-app/services/web3/hooks/types.ts
  wondrous-app/services/web3/hooks/useWonderWeb3.ts
  wondrous-app/theme/colors.ts
  wondrous-app/theme/palette.ts
  wondrous-app/utils/constants.ts
Labels: Ready for code review

#927 Guild token gating
  wondrous-app/.env.development
  wondrous-app/components/Button/index.tsx
  wondrous-app/components/Common/dropdown.tsx
  wondrous-app/components/FormField/CustomField.tsx
  wondrous-app/components/FormField/TextField.tsx
  wondrous-app/components/FormField/styles.tsx
  wondrous-app/components/Modal/index.tsx
  wondrous-app/components/Modal/styles.tsx
  wondrous-app/components/Settings/PaymentMethods/ConfigPaymentMethodModal.tsx
  wondrous-app/components/Settings/PaymentMethods/PaymentMethodList.tsx
  wondrous-app/components/Settings/PaymentMethods/styles.tsx
  wondrous-app/components/Settings/Roles/index.tsx
  wondrous-app/components/Settings/TokenGating/TokenGatingConditionDisplay.tsx
  wondrous-app/components/Settings/TokenGating/TokenGatingConditionList.tsx
  wondrous-app/components/Settings/TokenGating/TokenGatingConfigForm.tsx
  wondrous-app/components/Settings/TokenGating/TokenGatingGuildForm.tsx
  wondrous-app/components/Settings/TokenGating/TokenGatingModal.tsx
  wondrous-app/components/Settings/TokenGating/index.tsx
  wondrous-app/components/Settings/TokenGating/styles.tsx
  wondrous-app/components/Tabs/index.tsx
  wondrous-app/components/Tabs/styles.tsx
  wondrous-app/components/TokenGatingItem/TokenGatingActionMenu.tsx
  wondrous-app/components/TokenGatingItem/index.tsx
  wondrous-app/components/organization/wrapper/TokenGatedRoleDisplay.tsx
  wondrous-app/graphql/fragments/tokenGating.ts
  wondrous-app/graphql/mutations/tokenGating.ts
  wondrous-app/graphql/queries/org.ts
  wondrous-app/graphql/queries/pod.ts
  wondrous-app/graphql/queries/tokenGating.ts
  wondrous-app/pages/organization/settings/[orgId]/token-gating.tsx
  wondrous-app/pages/pod/settings/[podId]/roles.tsx
  wondrous-app/stories/Tabs/Tabs.stories.tsx
  wondrous-app/types/Guild.tsx
  wondrous-app/types/TokenGating.ts
  wondrous-app/utils/constants.ts
  wondrous-app/utils/contexts.ts
  wondrous-app/utils/hooks.ts
Labels: Ready for code review

#984 feat: pagination on batch payment view
  wondrous-app/components/Settings/Payouts/index.tsx
  wondrous-app/components/Settings/Payouts/styles.tsx
Labels: Ready for code review

#989 Fix: Missing button text on FireFox
  wondrous-app/components/ListViewAdmin/ColumnEntry.tsx
  wondrous-app/components/ListViewAdmin/styles.tsx
Labels: bug, Ready for code review

#992 feat: blur disabled payment methods
  wondrous-app/components/Settings/PaymentMethods/PaymentMethodList.tsx
  wondrous-app/components/Settings/PaymentMethods/styles.tsx
Labels: Ready for code review

#961 feat: add search to members page
  wondrous-app/components/Settings/Members/MembersTableRow/index.tsx
  wondrous-app/components/Settings/Members/MembersTableRow/styles.tsx
  wondrous-app/components/Settings/Members/index.tsx
  wondrous-app/components/Settings/Members/styles.tsx
  wondrous-app/graphql/queries/org.ts
  wondrous-app/graphql/queries/pod.ts
  wondrous-app/services/web3/hooks/types.ts
  wondrous-app/services/web3/hooks/useWonderWeb3.ts
Labels: Ready for code review

#1000 fix(kudos modal list view fix) - moved kudos modal out of the item
  wondrous-app/components/ListViewAdmin/ColumnEntry.tsx
  wondrous-app/components/ListViewAdmin/index.tsx
Labels: Ready for code review

#985 Add task observer
  wondrous-app/components/Button/index.tsx
  wondrous-app/components/Common/AvatarList/index.tsx
  wondrous-app/components/Common/TaskViewModal/taskViewModal.tsx
  wondrous-app/components/Common/TaskViewModal/taskViewModalFields/WatchersField.tsx
  wondrous-app/graphql/fragments/task.ts
  wondrous-app/graphql/mutations/task.ts
  wondrous-app/theme/colors.ts
  wondrous-app/theme/typography.ts
  wondrous-app/types/task.ts
Labels: WIP, Backend dependencies

#1002 hotfix: members page pagination
  wondrous-app/components/Settings/Members/index.tsx
  wondrous-app/components/Settings/Members/styles.tsx
Labels: Ready for code review

#1009 hotfix: broken staging
  wondrous-app/components/CreateCollaborationModal/Steps/AddTeamMembers/index.tsx
Labels: Ready for code review

#994 feat: coordinape installation
  wondrous-app/components/AppInstallation/Coordinape/CoordinapeIntegrationForm/constants.ts
  wondrous-app/components/AppInstallation/Coordinape/CoordinapeIntegrationForm/hooks.tsx
  wondrous-app/components/AppInstallation/Coordinape/CoordinapeIntegrationForm/index.tsx
  wondrous-app/components/AppInstallation/Coordinape/CoordinapeIntegrationForm/styles.tsx
  wondrous-app/components/AppInstallation/Coordinape/index.tsx
  wondrous-app/components/AppInstallation/Coordinape/styles.tsx
  wondrous-app/components/Icons/closeModal.tsx
  wondrous-app/components/Icons/ellipsesIcon.tsx
  wondrous-app/graphql/mutations/integration.ts
  wondrous-app/graphql/queries/user.ts
  wondrous-app/next.config.js
  wondrous-app/pages/apps/install/coordinape.tsx
  wondrous-app/utils/constants.ts
Labels: WIP

#1028 Fix: Observer styling
  wondrous-app/components/Common/AvatarList/index.tsx
  wondrous-app/components/Common/AvatarList/styles.tsx
  wondrous-app/components/Common/TaskViewModal/taskViewModalFields/WatchersField.tsx
Labels: bug, Ready for code review

#1023 hotfix: members page query key
  wondrous-app/components/Settings/MemberRoles/index.tsx
  wondrous-app/services/apollo.ts
Labels: Ready for code review

#1026 feat: members page role filter
  wondrous-app/components/Settings/MemberRoles/index.tsx
  wondrous-app/components/Settings/MemberRoles/styled.tsx
  wondrous-app/components/Settings/Members/index.tsx
  wondrous-app/graphql/queries/org.ts
  wondrous-app/graphql/queries/pod.ts
  wondrous-app/services/apollo.ts
Labels: Ready for code review

#1033 fixes on d2d ui
  wondrous-app/components/Settings/generalSettings.tsx
  wondrous-app/components/organization/wrapper/styles.tsx
Labels: Ready for code review
