Repository wondrous-dev/wondrous-frontend, pull requests merged in 2022-10, with the labels that each got.

#1068 wip: Improve discord notification config page
  wondrous-app/.eslintrc
  wondrous-app/components/Button/index.tsx
  wondrous-app/components/Common/Divider/index.tsx
  wondrous-app/components/RoleModal/RoleModalElement.tsx
  wondrous-app/components/Settings/Notifications/AddWonderBotToDiscordConfig.tsx
  wondrous-app/components/Settings/Notifications/ConnectDiscordServer.tsx
  wondrous-app/components/Settings/Notifications/DiscordIntegrationCard.tsx
  wondrous-app/components/Settings/Notifications/PodNotification.tsx
  wondrous-app/components/Settings/Notifications/constants.tsx
  wondrous-app/components/Settings/Notifications/index.tsx
  wondrous-app/components/Settings/Notifications/styles.tsx
  wondrous-app/components/Settings/Roles/index.tsx
  wondrous-app/graphql/mutations/notification.ts
  wondrous-app/graphql/queries/notifications.ts
  wondrous-app/pages/collaboration/settings/[orgId]/roles.tsx
  wondrous-app/pages/organization/settings/[orgId]/roles.tsx
  wondrous-app/stories/Button/Button.stories.tsx
  wondrous-app/utils/constants.ts
  wondrous-app/utils/orgPermissions.ts
  wondrous-app/utils/podPermissions.ts
Labels: WIP

#1099 Add priorities to tasks
  wondrous-app/components/Common/BountyBoard/index.tsx
  wondrous-app/components/Common/Filter/index.tsx
  wondrous-app/components/Common/Filter/styles.tsx
  wondrous-app/components/Common/MilestoneBoard/index.tsx
  wondrous-app/components/Common/Task/card.tsx
  wondrous-app/components/Common/TaskPriority/index.tsx
  wondrous-app/components/Common/TaskPriority/styles.tsx
  wondrous-app/components/Common/TaskPriorityToggleButton/index.tsx
  wondrous-app/components/Common/TaskPriorityToggleButton/styles.tsx
  wondrous-app/components/Common/TaskViewModal/taskViewModal.tsx
  wondrous-app/components/Common/TaskViewModal/taskViewModalFields.tsx
  wondrous-app/components/CreateEntity/CreateEntityModal/Helpers/hooks.tsx
  wondrous-app/components/CreateEntity/CreateEntityModal/Helpers/utils/index.tsx
  wondrous-app/components/CreateEntity/CreateEntityModal/index.tsx
  wondrous-app/components/CreateEntity/index.tsx
  wondrous-app/components/Dashboard/boards/index.tsx
  wondrous-app/components/Icons/PriorityHighIcon.tsx
  wondrous-app/components/Icons/PriorityIcon.tsx
  wondrous-app/components/Icons/PriorityLowIcon.tsx
  wondrous-app/components/Icons/PriorityMediumIcon.tsx
  wondrous-app/components/Icons/PriorityUrgentIcon.tsx
  wondrous-app/components/Settings/generalSettings.tsx
  wondrous-app/graphql/fragments/task.ts
  wondrous-app/graphql/queries/taskBoard.ts
  wondrous-app/package.json
  wondrous-app/pages/collaboration/[username]/boards.tsx
  wondrous-app/pages/organization/[username]/boards.tsx
  wondrous-app/pages/pod/[podId]/boards.tsx
  wondrous-app/services/apollo.ts
  wondrous-app/services/board.tsx
  wondrous-app/services/payment.tsx
  wondrous-app/stories/Buttons/Button.stories.tsx
  wondrous-app/stories/Task/PriorityChip.stories.tsx
  wondrous-app/stories/Task/PriorityToggleButton.stories.tsx
  wondrous-app/theme/colors.ts
  wondrous-app/types/task.ts
  wondrous-app/utils/constants.tsx
Labels: Ready for code review

#1118 feat: clickable pods and contributors
  wondrous-app/components/Pod/wrapper/index.tsx
  wondrous-app/components/organization/wrapper/styles.tsx
Labels: Ready for code review

#1125 feat: payment ledger revamp
  wondrous-app/components/Button/index.tsx
  wondrous-app/components/Icons/QuestionMarkIcon.tsx
  wondrous-app/components/Settings/Payouts/PayoutItem.tsx
  wondrous-app/components/Settings/Payouts/PayoutTable.tsx
  wondrous-app/components/Settings/Payouts/constants.tsx
  wondrous-app/components/Settings/Payouts/hooks.tsx
  wondrous-app/components/Settings/Payouts/index.tsx
  wondrous-app/components/Settings/Payouts/styles.tsx
  wondrous-app/components/Settings/styles.tsx
  wondrous-app/graphql/fragments/payment.ts
  wondrous-app/graphql/queries/payment.ts
Labels: Ready for code review

#1098 feat: import tasks from csv
  wondrous-app/components/Common/CSVFileDropZone/index.tsx
  wondrous-app/components/Common/CSVFileDropZone/styles.tsx
  wondrous-app/components/Icons/DocumentIcon.tsx
  wondrous-app/components/Icons/trello.svg
  wondrous-app/components/Settings/TaskImport/GenericImportTaskModal/constants.tsx
  wondrous-app/components/Settings/TaskImport/GenericImportTaskModal/helpers.ts
  wondrous-app/components/Settings/TaskImport/GenericImportTaskModal/index.tsx
  wondrous-app/components/Settings/TaskImport/GenericImportTaskModal/styles.tsx
  wondrous-app/components/Settings/TaskImport/ImportTaskFromCSV.tsx
  wondrous-app/components/Settings/TaskImport/index.tsx
  wondrous-app/components/Settings/TaskImport/styles.tsx
  wondrous-app/graphql/mutations/task.ts
  wondrous-app/package.json
  wondrous-app/yarn.lock
Labels: Ready for code review

#1144 Staging
  wondrous-app/components/Collaboration/Boards.tsx
  wondrous-app/components/Comment/index.tsx
  wondrous-app/components/Common/ArchiveTaskModal/index.tsx
  wondrous-app/components/Common/TaskSubmission/submissionForm.tsx
  wondrous-app/components/Common/TaskViewModal/taskList.tsx
  wondrous-app/components/CreateCollaborationModal/Steps/AddTeamMembers/index.tsx
  wondrous-app/components/CreateEntity/CreateEntityModal/Helpers/hooks.tsx
  wondrous-app/components/CreateEntity/CreateEntityModal/PodSearch/index.tsx
  wondrous-app/components/CreateEntity/CreateEntityModal/index.tsx
  wondrous-app/components/CreateEntity/CreateEntityModal/styles.tsx
  wondrous-app/components/CreateEntity/CreatePodModal.tsx
  wondrous-app/components/Dashboard/bounties/index.tsx
  wondrous-app/components/Pod/wrapper/index.tsx
  wondrous-app/components/Settings/Members/InviteMember.tsx
  wondrous-app/components/organization/analytics/index.tsx
  wondrous-app/graphql/queries/org.ts
  wondrous-app/graphql/queries/taskBoard.ts
  wondrous-app/pages/collaboration/[username]/boards.tsx
  wondrous-app/pages/organization/[username]/boards.tsx
  wondrous-app/services/apollo.ts
Labels: Backend dependencies

#1137 feat: pod page
  wondrous-app/components/Common/RolePill/index.tsx
  wondrous-app/components/Common/SidebarEntityList/index.tsx
  wondrous-app/components/Settings/Members/MembersTableRow/helpers.ts
  wondrous-app/components/organization/pods/PodItem/index.tsx
  wondrous-app/components/organization/pods/PodItem/styles.tsx
  wondrous-app/components/organization/pods/constants.tsx
  wondrous-app/components/organization/pods/index.tsx
  wondrous-app/components/organization/pods/styles.tsx
  wondrous-app/pages/organization/[username]/pods.tsx
  wondrous-app/utils/common.tsx
  wondrous-app/utils/constants.tsx
Labels: Ready for code review

#1141 Link previews for task links and invite links
  wondrous-app/components/Auth/withAuth.tsx
  wondrous-app/components/MetaTags/index.tsx
  wondrous-app/pages/collaboration/[username]/boards.tsx
  wondrous-app/pages/dashboard/bounties.tsx
  wondrous-app/pages/dashboard/index.tsx
  wondrous-app/pages/dashboard/proposals.tsx
  wondrous-app/pages/invite/[token].tsx
  wondrous-app/pages/organization/[username]/boards.tsx
  wondrous-app/pages/pod/[podId]/boards.tsx
  wondrous-app/utils/board.tsx
Labels: Ready for code review

#1154 Staging
  wondrous-app/components/Auth/withAuth.tsx
  wondrous-app/components/Comment/index.tsx
  wondrous-app/components/Common/BountyBoard/index.tsx
  wondrous-app/components/Common/CommentItem/index.tsx
  wondrous-app/components/Common/Status/constants.tsx
  wondrous-app/components/Common/Status/index.tsx
  wondrous-app/components/Common/Status/styles.tsx
  wondrous-app/components/Common/SubmissionCommentType/index.tsx
  wondrous-app/components/Common/SubmissionStatus/index.tsx
  wondrous-app/components/Common/TaskSubmission/submissionForm.tsx
  wondrous-app/components/Common/TaskSubmission/submissionItem.tsx
  wondrous-app/components/Common/TaskViewModal/taskViewModal.tsx
  wondrous-app/components/CreateCollaborationModal/Steps/AddTeamMembers/index.tsx
  wondrous-app/components/CreateEntity/CreateEntityModal/Helpers/hooks.tsx
  wondrous-app/components/CreateEntity/CreatePodModal.tsx
  wondrous-app/components/MetaTags/index.tsx
  wondrous-app/components/Settings/Members/InviteMember.tsx
  wondrous-app/components/Settings/generalSettings.tsx
  wondrous-app/components/Settings/profileSettings.tsx
  wondrous-app/components/organization/analytics/index.tsx
  wondrous-app/graphql/mutations/taskSubmission.ts
  wondrous-app/graphql/queries/org.ts
  wondrous-app/pages/collaboration/[username]/boards.tsx
  wondrous-app/pages/dashboard/bounties.tsx
  wondrous-app/pages/dashboard/index.tsx
  wondrous-app/pages/dashboard/proposals.tsx
  wondrous-app/pages/invite/[token].tsx
  wondrous-app/pages/organization/[username]/boards.tsx
  wondrous-app/pages/pod/[podId]/boards.tsx
  wondrous-app/services/apollo.ts
  wondrous-app/utils/board.tsx
  wondrous-app/utils/constants.tsx
Labels: Backend dependencies

#1164 Bugfix/fix milestone task update
  wondrous-app/components/Common/TaskMenuStatus.tsx
  wondrous-app/hooks/useGetMilestoneTasksProgress.ts
Labels: Ready for code review
