Repository wondrous-dev/wondrous-frontend, pull requests merged in 2022-05, with the labels that each got.

#463 Notification settings
  wondrous-app/components/Common/Switch/index.tsx
  wondrous-app/components/Settings/Notifications/profile.tsx
  wondrous-app/components/Settings/Notifications/styles.tsx
  wondrous-app/components/Settings/styles.tsx
  wondrous-app/graphql/mutations/notification.ts
  wondrous-app/graphql/queries/notifications.ts
Labels: Ready for code review

#465 Update member settings page to match designs
  wondrous-app/components/Common/DropdownSelect/dropdownSelect.tsx
  wondrous-app/components/Common/DropdownSelect/styles.tsx
  wondrous-app/components/CreateEntity/styles.tsx
  wondrous-app/components/Icons/arrowDropDown.tsx
  wondrous-app/components/Icons/membersSettings.tsx
  wondrous-app/components/Icons/more.tsx
  wondrous-app/components/Icons/podIconWithoutBg.tsx
  wondrous-app/components/Icons/roles.tsx
  wondrous-app/components/Icons/search.tsx
  wondrous-app/components/Settings/MemberRoles/index.tsx
  wondrous-app/components/Settings/MemberRoles/styled.tsx
  wondrous-app/components/Settings/Members/InviteMember.tsx
  wondrous-app/components/Settings/Members/MemberRoleDropdown.tsx
  wondrous-app/components/Settings/Members/helpers.tsx
  wondrous-app/components/Settings/Members/index.tsx
  wondrous-app/components/Settings/Members/styles.tsx
  wondrous-app/components/Settings/Roles/styles.tsx
  wondrous-app/components/Settings/settingsWrapper.tsx
  wondrous-app/components/Settings/styles.tsx
  wondrous-app/components/styled/Tag.tsx
  wondrous-app/components/styled/Text.tsx
  wondrous-app/components/styled/index.tsx
  wondrous-app/graphql/queries/org.ts
  wondrous-app/graphql/queries/pod.ts
  wondrous-app/package-lock.json
Labels: Ready for code review

#509 Confirmation modal before remove member from the POD/DAO
  wondrous-app/components/Common/ConfirmModal/index.tsx
  wondrous-app/components/Common/ConfirmModal/styled.tsx
  wondrous-app/components/Settings/Members/index.tsx
Labels: Ready for code review

#517 Search bar should have loading and display 'no result' if no result found
  wondrous-app/components/SearchTasks/index.tsx
  wondrous-app/theme/stylesheets/globals.css
Labels: Ready for code review

#536 Change the color of the "no results" on the search drop down
  wondrous-app/components/SearchTasks/index.tsx
  wondrous-app/components/SearchTasks/styles.tsx
  wondrous-app/theme/stylesheets/globals.css
Labels: Ready for code review

#312 Tagging tasks and milestones
  wondrous-app/.env.development
  wondrous-app/components/Common/Task/modal.tsx
  wondrous-app/components/Common/Task/styles.tsx
  wondrous-app/components/CreateEntity/createEntityModal.tsx
  wondrous-app/components/CreateEntity/editEntityModal.tsx
  wondrous-app/components/CreateEntity/styles.tsx
  wondrous-app/components/DocumentGridItem/DocumentGridItem.tsx
  wondrous-app/components/DocumentListItem/DocumentListItem.tsx
  wondrous-app/components/Icons/tagsIcon.tsx
  wondrous-app/components/Tags/index.tsx
  wondrous-app/components/Tags/styles.tsx
  wondrous-app/graphql/fragments/org.ts
  wondrous-app/graphql/fragments/task.ts
  wondrous-app/graphql/mutations/org.ts
  wondrous-app/graphql/queries/org.ts
  wondrous-app/utils/colors.tsx
  wondrous-app/utils/constants.ts
Labels: Ready for code review, Backend dependencies

#557 fix: Color shuffling not working for tags
  wondrous-app/components/Tags/index.tsx
  wondrous-app/components/Tags/styles.tsx
Labels: bug, Ready for code review
